# Generated by Django 3.2.9 on 2022-01-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdata',
            name='ale_date_time111',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
