# Generated by Django 3.2.9 on 2022-01-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_salesdata_ale_date_time111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdata',
            name='ale_date_time111',
        ),
    ]
