# Generated by Django 3.2.9 on 2022-01-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_delete_weekly_salesdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdata',
            name='weekly_sales',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
