# Generated by Django 3.2.9 on 2022-01-14 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_remove_salesdata_sku_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdata',
            name='user',
        ),
    ]
