# Generated by Django 3.2.9 on 2022-01-14 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_remove_salesdata_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesdata',
            old_name='updated_on',
            new_name='last_updated_date',
        ),
    ]
