# Generated by Django 3.2.9 on 2022-01-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_auto_20220114_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='local_sales_retail',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
