# Generated by Django 3.2.9 on 2022-01-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_alter_salesdata_local_sales_retail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='local_sales_retail',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
