# Generated by Django 3.2.9 on 2022-01-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_alter_salesdata_local_sales_retail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='grand_total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='local_sales_dealer',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='local_sales_hawker',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='local_sales_modern_trade',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='other_issues_damage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='other_issues_other',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='other_issues_return',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='other_sales_dealer',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='other_sales_modern_trade',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='other_sales_reatil',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='outstation_sales_dealer',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='outstation_sales_hawker',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='outstation_sales_modern_trade',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='outstation_sales_reatil',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='total_issue',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='total_local_sales',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='total_other_sales',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='total_outstation_sales',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
