# Generated by Django 3.2.9 on 2022-01-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_auto_20220114_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesdata',
            old_name='sale_date_time',
            new_name='sales_date_time',
        ),
    ]
