# Generated by Django 3.2.9 on 2022-01-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_rename_sale_date_time_salesdata_sales_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesdata',
            old_name='source',
            new_name='tranisition_type',
        ),
    ]
