# Generated by Django 3.2.9 on 2022-01-17 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_rename_source_salesdata_tranisition_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salesdata',
            table='transition_salesdata',
        ),
    ]
