# Generated by Django 3.2.9 on 2022-01-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0016_auto_20220117_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdata',
            name='tranisition_source',
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='tranisition_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
