# Generated by Django 3.2.9 on 2022-01-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0017_auto_20220117_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesdata',
            old_name='tranisition_type',
            new_name='tranisition_source',
        ),
    ]
