# Generated by Django 3.2.9 on 2022-01-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0018_rename_tranisition_type_salesdata_tranisition_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdata',
            name='tranisition_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
