# Generated by Django 3.2.9 on 2022-01-17 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0019_salesdata_tranisition_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sku_remarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_category', models.CharField(blank=True, max_length=20, null=True)),
                ('sku_id', models.CharField(blank=True, max_length=100, null=True)),
                ('wd_id', models.CharField(blank=True, max_length=100, null=True)),
                ('town_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='sku_master_product',
            old_name='created_on',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='sku_master_product',
            old_name='updated_by',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='sku_master_product',
            old_name='updated_on',
            new_name='last_updated_date',
        ),
        migrations.RenameField(
            model_name='wdskucatagory',
            old_name='created_on',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='wdskucatagory',
            old_name='updated_by',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='wdskucatagory',
            old_name='updated_on',
            new_name='last_updated_date',
        ),
        migrations.AddField(
            model_name='sku_type',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sku_type',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sku_type',
            name='last_updated',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sku_type',
            name='last_updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Sku_remindar',
        ),
    ]
