# Generated by Django 3.2.9 on 2022-01-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0020_auto_20220117_1701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GPIWeeklySales',
        ),
    ]
