# Generated by Django 3.2.9 on 2022-01-17 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_delete_gpiweeklysales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_hierarchy_master',
            old_name='created_on',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='sales_hierarchy_master',
            old_name='updated_by',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='sales_hierarchy_master',
            old_name='updated_on',
            new_name='last_updated_date',
        ),
    ]
