# Generated by Django 3.2.9 on 2022-01-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0022_auto_20220117_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku_master_product',
            name='cnf_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
