# Generated by Django 3.2.9 on 2022-01-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0023_alter_sku_master_product_cnf_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='sales_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
