# Generated by Django 3.2.9 on 2022-01-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0029_alter_salesdata_sales_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku_remarks',
            name='user',
        ),
        migrations.AddField(
            model_name='sku_remarks',
            name='sales_date_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
