# Generated by Django 3.2.9 on 2022-01-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0031_remove_sku_remarks_sku_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transition_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date_time', models.DateField(blank=True, null=True)),
                ('total_distributer_sale', models.IntegerField(blank=True, null=True)),
                ('total_insart_sale', models.IntegerField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transition_history',
            },
        ),
    ]
