# Generated by Django 3.2.9 on 2022-01-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0032_transition_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition_history',
            name='tranisition_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
