# Generated by Django 3.2.9 on 2022-02-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0034_archived_salesdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='archived_salesdata',
            name='archived_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
