# Generated by Django 3.2.9 on 2022-02-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0035_archived_salesdata_archived_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transition_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.CharField(blank=True, max_length=100, null=True)),
                ('wd_id', models.CharField(blank=True, max_length=100, null=True)),
                ('town_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Transition_log',
            },
        ),
    ]
