# Generated by Django 3.2.9 on 2022-02-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0038_auto_20220210_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku_remarks',
            old_name='tranisition_type',
            new_name='remarks_type',
        ),
    ]
