# Generated by Django 3.2.9 on 2022-02-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0039_rename_tranisition_type_sku_remarks_remarks_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdata',
            name='cnf_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='company',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='region',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='unit_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sku_master_product',
            name='company',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sku_master_product',
            name='unit_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
