# Generated by Django 3.2.9 on 2022-02-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0040_auto_20220215_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='WD_SKU_Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(blank=True, max_length=50, null=True)),
                ('wd_town_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sku_id', models.CharField(blank=True, max_length=50, null=True)),
                ('cnf_id', models.CharField(blank=True, max_length=50, null=True)),
                ('cnf_code', models.CharField(blank=True, max_length=50, null=True)),
                ('order_month_year', models.CharField(blank=True, max_length=50, null=True)),
                ('last_price', models.FloatField(default=0)),
                ('active_flag', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'master_wd_sku__mapping',
            },
        ),
    ]
