# Generated by Django 3.2.9 on 2022-02-16 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0041_wd_sku_mapping'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wd_sku_mapping',
            table='master_wd_sku_mapping',
        ),
    ]
