# Generated by Django 3.2.9 on 2022-02-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0042_alter_wd_sku_mapping_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WD_SKU_Mapping',
        ),
        migrations.AddField(
            model_name='wdskucatagory',
            name='cnf_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wdskucatagory',
            name='last_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='wdskucatagory',
            name='order_month_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
