# Generated by Django 3.2.9 on 2022-02-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0043_auto_20220217_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition_log',
            name='sale_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
