# Generated by Django 3.2.9 on 2022-02-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0045_alter_transition_log_sale_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transition_log',
            name='sale_date_time',
        ),
        migrations.AddField(
            model_name='transition_log',
            name='sales_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
