# Generated by Django 3.2.9 on 2022-02-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0046_auto_20220218_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archived_salesdata',
            name='weekly_sales',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='weekly_sales',
        ),
        migrations.AddField(
            model_name='archived_salesdata',
            name='cnf_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='archived_salesdata',
            name='company',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='archived_salesdata',
            name='region',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='archived_salesdata',
            name='unit_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='archived_salesdata',
            name='value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
