# Generated by Django 3.2.9 on 2022-02-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0047_auto_20220218_1421'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transition_log',
            new_name='Integration_log_details',
        ),
        migrations.RenameModel(
            old_name='Transition_history',
            new_name='Integration_log_summary',
        ),
        migrations.RenameField(
            model_name='archived_salesdata',
            old_name='freez_status',
            new_name='freeze_status',
        ),
        migrations.RenameField(
            model_name='archived_salesdata',
            old_name='other_sales_reatil',
            new_name='other_sales_retail',
        ),
        migrations.RenameField(
            model_name='archived_salesdata',
            old_name='tranisition_source',
            new_name='transaction_source',
        ),
        migrations.RenameField(
            model_name='archived_salesdata',
            old_name='tranisition_type',
            new_name='transaction_type',
        ),
        migrations.RenameField(
            model_name='integration_log_summary',
            old_name='sale_date_time',
            new_name='sale_date',
        ),
        migrations.RenameField(
            model_name='salesdata',
            old_name='freez_status',
            new_name='freeze_status',
        ),
        migrations.RenameField(
            model_name='salesdata',
            old_name='other_sales_reatil',
            new_name='other_sales_retail',
        ),
        migrations.RenameField(
            model_name='salesdata',
            old_name='tranisition_source',
            new_name='transaction_source',
        ),
        migrations.RenameField(
            model_name='salesdata',
            old_name='tranisition_type',
            new_name='transaction_type',
        ),
        migrations.AlterModelTable(
            name='integration_log_details',
            table='integration_log_details',
        ),
        migrations.AlterModelTable(
            name='integration_log_summary',
            table='integration_log_summary',
        ),
        migrations.AlterModelTable(
            name='salesdata',
            table='transaction_salesdata',
        ),
    ]
