# Generated by Django 3.2.9 on 2022-02-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0048_auto_20220221_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration_log_summary',
            name='status',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
