# Generated by Django 3.2.9 on 2022-02-21 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0049_integration_log_summary_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integration_log_summary',
            name='status',
        ),
    ]
