# Generated by Django 3.2.9 on 2022-03-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0050_remove_integration_log_summary_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration_log_summary',
            name='email_status',
            field=models.BooleanField(default=False),
        ),
    ]
