# Generated by Django 3.2.9 on 2022-03-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0051_integration_log_summary_email_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration_log_details',
            name='repeat_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
