# Generated by Django 3.2.9 on 2022-04-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0052_integration_log_details_repeat_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candy_JAR_GMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sku_code', models.CharField(blank=True, max_length=50, null=True)),
                ('sku_name', models.CharField(blank=True, max_length=50, null=True)),
                ('sku_short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('jar_size_gms', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'candy_conversion_jar_gms',
            },
        ),
    ]
