# Generated by Django 3.2.9 on 2022-04-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0053_candy_jar_gms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_sku_sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=25, null=True)),
                ('town_id', models.CharField(blank=True, max_length=25, null=True)),
                ('wd_id', models.CharField(blank=True, max_length=25, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=25, null=True)),
                ('local_retail_total', models.FloatField(blank=True, default=0, null=True)),
                ('local_dealer_total', models.FloatField(blank=True, default=0, null=True)),
                ('local_hawker_total', models.FloatField(blank=True, default=0, null=True)),
                ('local_m_total', models.FloatField(blank=True, default=0, null=True)),
                ('total_local', models.FloatField(blank=True, default=0, null=True)),
                ('outstation_retail_total', models.FloatField(blank=True, default=0, null=True)),
                ('outstation_dealer_total', models.FloatField(blank=True, default=0, null=True)),
                ('outstation_hawker_total', models.FloatField(blank=True, default=0, null=True)),
                ('outstation_m_total', models.FloatField(blank=True, default=0, null=True)),
                ('outstation_total', models.FloatField(blank=True, default=0, null=True)),
                ('other_retail_total', models.FloatField(blank=True, default=0, null=True)),
                ('other_dealer_total', models.FloatField(blank=True, default=0, null=True)),
                ('other_hawker_total', models.FloatField(blank=True, default=0, null=True)),
                ('other_total', models.FloatField(blank=True, default=0, null=True)),
                ('total_retail_total', models.FloatField(blank=True, default=0, null=True)),
                ('total_detail_total', models.FloatField(blank=True, default=0, null=True)),
                ('total_hawker_total', models.FloatField(blank=True, default=0, null=True)),
                ('total_m_trade_total', models.FloatField(blank=True, default=0, null=True)),
                ('all_total', models.FloatField(blank=True, default=0, null=True)),
                ('other_issued_damage_total', models.FloatField(blank=True, default=0, null=True)),
                ('other_issued_return_total', models.FloatField(blank=True, default=0, null=True)),
                ('other_issued_other_total', models.FloatField(blank=True, default=0, null=True)),
                ('total_issued', models.FloatField(blank=True, default=0, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transaction_total_sku_sales',
            },
        ),
    ]
