# Generated by Django 3.2.9 on 2022-04-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0054_total_sku_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='total_sku_sales',
            old_name='other_hawker_total',
            new_name='other_m_total',
        ),
    ]
