# Generated by Django 3.2.9 on 2022-05-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0056_repeat_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_hierarchy_master',
            name='wd_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='wd_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
