# Generated by Django 3.2.9 on 2022-05-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0058_auto_20220504_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_hierarchy_master',
            name='town_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='brand_category',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='sales_date_time',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='sku_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='town_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
