# Generated by Django 3.2.9 on 2022-05-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0060_auto_20220504_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archived_salesdata',
            name='sku_code',
        ),
        migrations.RemoveField(
            model_name='archived_salesdata',
            name='sku_short_name',
        ),
        migrations.RemoveField(
            model_name='archived_salesdata',
            name='town_code',
        ),
        migrations.RemoveField(
            model_name='archived_salesdata',
            name='wd_name',
        ),
        migrations.RemoveField(
            model_name='archived_salesdata',
            name='wd_type',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='sku_code',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='sku_short_name',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='town_code',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='wd_name',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='wd_type',
        ),
        migrations.AlterField(
            model_name='sales_hierarchy_master',
            name='town_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_hierarchy_master',
            name='wd_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='brand_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='sales_date_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='sku_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='town_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='wd_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
