# Generated by Django 3.2.9 on 2022-05-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0061_auto_20220504_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='archived_salesdata',
            name='sku_code',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='archived_salesdata',
            name='sku_short_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='archived_salesdata',
            name='town_code',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='archived_salesdata',
            name='wd_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='archived_salesdata',
            name='wd_type',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='sku_code',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='sku_short_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='town_code',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='wd_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='wd_type',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
