# Generated by Django 3.2.9 on 2022-05-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0063_auto_20220505_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdata',
            name='town_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='town_code',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
