# Generated by Django 3.2.9 on 2022-05-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0064_auto_20220505_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archived_salesdata',
            name='town_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repeat_count',
            name='town_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='town_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
