# Generated by Django 3.2.9 on 2022-05-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0065_auto_20220506_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdata',
            name='distrcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
