# Generated by Django 3.2.9 on 2022-08-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0069_auto_20220624_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku_master_product',
            name='calculated_by',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
