# Generated by Django 3.2.9 on 2022-09-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0070_sku_master_product_calculated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration_log_summary',
            name='invalid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='integration_log_summary',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
