# Generated by Django 3.2.9 on 2022-09-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0072_temp_total_sku_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temp_total_sku_sales',
            old_name='all_total',
            new_name='grand_total',
        ),
        migrations.RenameField(
            model_name='temp_total_sku_sales',
            old_name='updated_date',
            new_name='last_updated_date',
        ),
        migrations.RenameField(
            model_name='temp_total_sku_sales',
            old_name='local_dealer_total',
            new_name='local_sales_dealer',
        ),
        migrations.RenameField(
            model_name='temp_total_sku_sales',
            old_name='local_m_total',
            new_name='local_sales_hawker',
        ),
        migrations.RenameField(
            model_name='temp_total_sku_sales',
            old_name='local_hawker_total',
            new_name='local_sales_modern_trade',
        ),
        migrations.RenameField(
            model_name='temp_total_sku_sales',
            old_name='local_retail_total',
            new_name='local_sales_retail',
        ),
        migrations.RenameField(
            model_name='temp_total_sku_sales',
            old_name='other_dealer_total',
            new_name='other_issues_damage',
        ),
        migrations.RenameField(
            model_name='temp_total_sku_sales',
            old_name='other_issued_damage_total',
            new_name='other_issues_other',
        ),
        migrations.RenameField(
            model_name='temp_total_sku_sales',
            old_name='other_issued_other_total',
            new_name='other_issues_return',
        ),
        migrations.RenameField(
            model_name='temp_total_sku_sales',
            old_name='other_issued_return_total',
            new_name='other_sales_dealer',
        ),
        migrations.RenameField(
            model_name='temp_total_sku_sales',
            old_name='other_m_total',
            new_name='other_sales_modern_trade',
        ),
        migrations.RenameField(
            model_name='temp_total_sku_sales',
            old_name='other_retail_total',
            new_name='other_sales_retail',
        ),
        migrations.RenameField(
            model_name='temp_total_sku_sales',
            old_name='outstation_dealer_total',
            new_name='outstation_sales_dealer',
        ),
        migrations.RenameField(
            model_name='temp_total_sku_sales',
            old_name='other_total',
            new_name='outstation_sales_hawker',
        ),
        migrations.RenameField(
            model_name='temp_total_sku_sales',
            old_name='outstation_hawker_total',
            new_name='outstation_sales_modern_trade',
        ),
        migrations.RenameField(
            model_name='temp_total_sku_sales',
            old_name='outstation_m_total',
            new_name='outstation_sales_reatil',
        ),
        migrations.RenameField(
            model_name='temp_total_sku_sales',
            old_name='sale_date',
            new_name='sales_date_time',
        ),
        migrations.RenameField(
            model_name='temp_total_sku_sales',
            old_name='outstation_retail_total',
            new_name='total_issue',
        ),
        migrations.RenameField(
            model_name='temp_total_sku_sales',
            old_name='outstation_total',
            new_name='total_local_sales',
        ),
        migrations.RenameField(
            model_name='temp_total_sku_sales',
            old_name='total_detail_total',
            new_name='total_other_sales',
        ),
        migrations.RenameField(
            model_name='temp_total_sku_sales',
            old_name='total_hawker_total',
            new_name='total_outstation_sales',
        ),
        migrations.RenameField(
            model_name='temp_total_sku_sales',
            old_name='total_issued',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='temp_total_sku_sales',
            old_name='total_local',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='temp_total_sku_sales',
            name='category',
        ),
        migrations.RemoveField(
            model_name='temp_total_sku_sales',
            name='total_m_trade_total',
        ),
        migrations.RemoveField(
            model_name='temp_total_sku_sales',
            name='total_retail_total',
        ),
        migrations.AddField(
            model_name='temp_total_sku_sales',
            name='brand_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='temp_total_sku_sales',
            name='cnf_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='temp_total_sku_sales',
            name='company',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='temp_total_sku_sales',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temp_total_sku_sales',
            name='distrcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='temp_total_sku_sales',
            name='freeze_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='temp_total_sku_sales',
            name='last_updated',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temp_total_sku_sales',
            name='region',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='temp_total_sku_sales',
            name='sku_code',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='temp_total_sku_sales',
            name='sku_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temp_total_sku_sales',
            name='sku_short_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='temp_total_sku_sales',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='temp_total_sku_sales',
            name='town_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='temp_total_sku_sales',
            name='town_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='temp_total_sku_sales',
            name='transaction_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='temp_total_sku_sales',
            name='wd_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='temp_total_sku_sales',
            name='wd_type',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='temp_total_sku_sales',
            name='town_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='temp_total_sku_sales',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='temp_total_sku_sales',
            name='wd_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
