# Generated by Django 3.2.9 on 2022-12-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0073_auto_20220909_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='archived_salesdata',
            name='gpi_tate',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='archived_salesdata',
            name='state',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='archived_salesdata',
            name='zone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='gpi_tate',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='state',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='zone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='temp_total_sku_sales',
            name='gpi_tate',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='temp_total_sku_sales',
            name='state',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='temp_total_sku_sales',
            name='zone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
