# Generated by Django 3.2.9 on 2022-12-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0074_auto_20221202_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archived_salesdata',
            old_name='gpi_tate',
            new_name='gpi_state',
        ),
        migrations.RenameField(
            model_name='archived_salesdata',
            old_name='state',
            new_name='statename',
        ),
        migrations.RenameField(
            model_name='salesdata',
            old_name='gpi_tate',
            new_name='gpi_state',
        ),
        migrations.RenameField(
            model_name='salesdata',
            old_name='state',
            new_name='statename',
        ),
        migrations.RenameField(
            model_name='temp_total_sku_sales',
            old_name='gpi_tate',
            new_name='gpi_state',
        ),
        migrations.RenameField(
            model_name='temp_total_sku_sales',
            old_name='state',
            new_name='statename',
        ),
    ]
