# Generated by Django 3.2.9 on 2022-12-15 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0076_apistatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apistatus',
        ),
    ]
