# Generated by Django 3.2.9 on 2023-01-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0080_auto_20230117_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_users',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='email_users',
            name='use_for',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='use_for',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
