# Generated by Django 3.2 on 2023-03-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0081_auto_20230117_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
