# Generated by Django 3.2 on 2023-03-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0082_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
