# Generated by Django 3.2.9 on 2023-03-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0083_delete_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
    ]
