# Generated by Django 3.2 on 2023-03-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0084_alter_salesdata_grand_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData_7days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_category', models.CharField(blank=True, max_length=20, null=True)),
                ('sku_id', models.CharField(blank=True, max_length=100, null=True)),
                ('wd_id', models.CharField(blank=True, max_length=100, null=True)),
                ('town_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_date_time', models.DateField(blank=True, null=True)),
                ('local_sales_retail', models.FloatField(blank=True, default=0, null=True)),
                ('local_sales_dealer', models.FloatField(blank=True, default=0, null=True)),
                ('local_sales_modern_trade', models.FloatField(blank=True, default=0, null=True)),
                ('local_sales_hawker', models.FloatField(blank=True, default=0, null=True)),
                ('total_local_sales', models.FloatField(blank=True, default=0, null=True)),
                ('outstation_sales_reatil', models.FloatField(blank=True, default=0, null=True)),
                ('outstation_sales_dealer', models.FloatField(blank=True, default=0, null=True)),
                ('outstation_sales_modern_trade', models.FloatField(blank=True, default=0, null=True)),
                ('outstation_sales_hawker', models.FloatField(blank=True, default=0, null=True)),
                ('total_outstation_sales', models.FloatField(blank=True, default=0, null=True)),
                ('other_sales_retail', models.FloatField(blank=True, default=0, null=True)),
                ('other_sales_dealer', models.FloatField(blank=True, default=0, null=True)),
                ('other_sales_modern_trade', models.FloatField(blank=True, default=0, null=True)),
                ('total_other_sales', models.FloatField(blank=True, default=0, null=True)),
                ('other_issues_damage', models.FloatField(blank=True, default=0, null=True)),
                ('other_issues_return', models.FloatField(blank=True, default=0, null=True)),
                ('other_issues_other', models.FloatField(blank=True, default=0, null=True)),
                ('total_issue', models.FloatField(blank=True, default=0, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_source', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('freeze_status', models.BooleanField(default=False)),
                ('transaction_type', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=60, null=True)),
                ('unit_price', models.FloatField(blank=True, default=0, null=True)),
                ('region', models.CharField(blank=True, max_length=60, null=True)),
                ('cnf_id', models.CharField(blank=True, max_length=60, null=True)),
                ('value', models.FloatField(blank=True, default=0, null=True)),
                ('wd_name', models.CharField(blank=True, max_length=60, null=True)),
                ('wd_type', models.CharField(blank=True, max_length=60, null=True)),
                ('sku_code', models.CharField(blank=True, max_length=60, null=True)),
                ('sku_short_name', models.CharField(blank=True, max_length=60, null=True)),
                ('town_name', models.CharField(blank=True, max_length=60, null=True)),
                ('town_code', models.CharField(blank=True, max_length=150, null=True)),
                ('distrcode', models.CharField(blank=True, max_length=50, null=True)),
                ('zone', models.CharField(blank=True, max_length=150, null=True)),
                ('statename', models.CharField(blank=True, max_length=150, null=True)),
                ('gpi_state', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'transaction_salesdata_last7days',
            },
        ),
    ]
