# Generated by Django 3.2 on 2023-04-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0085_salesdata_7days'),
    ]

    operations = [
        migrations.AddField(
            model_name='apistatus',
            name='sfa_bulk_flag',
            field=models.BooleanField(default=False),
        ),
    ]
