# Generated by Django 3.2 on 2023-08-25 22:10

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('user_type', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_by', models.CharField(blank=True, max_length=101, null=True)),
                ('first_login', models.BooleanField(default=False)),
                ('lock_unlock', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/')),
                ('locationcode', models.CharField(blank=True, max_length=100, null=True)),
                ('is_logedin', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_reset_password', models.BooleanField(default=False)),
                ('reset_password_date', models.DateTimeField(blank=True, null=True)),
                ('invalid_login', models.PositiveIntegerField(default=0)),
                ('last_acive_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('first_attempt', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_attempt', models.DateTimeField(auto_now_add=True, null=True)),
                ('raw_password', models.CharField(blank=True, max_length=50, null=True)),
                ('last_reset_time', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'master_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Access_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user_type', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_save_date', models.DateField(blank=True, max_length=100, null=True)),
                ('town_code', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=20, null=True)),
                ('count', models.IntegerField(default=1)),
                ('town', models.CharField(blank=True, max_length=150, null=True)),
                ('wd_name', models.CharField(blank=True, max_length=150, null=True)),
                ('zone', models.CharField(blank=True, max_length=150, null=True)),
                ('statename', models.CharField(blank=True, max_length=150, null=True)),
                ('gpi_state', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'access_log',
            },
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=25, null=True)),
                ('user_type', models.CharField(blank=True, max_length=30, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('login_count', models.IntegerField(default=1)),
                ('zone', models.CharField(blank=True, max_length=150, null=True)),
                ('statename', models.CharField(blank=True, max_length=150, null=True)),
                ('gpi_state', models.CharField(blank=True, max_length=150, null=True)),
                ('town', models.CharField(blank=True, max_length=150, null=True)),
                ('wd_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'master_user_attendance',
            },
        ),
        migrations.CreateModel(
            name='Password_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=15, null=True)),
                ('user_type', models.CharField(blank=True, max_length=20, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user_password_histrory',
            },
        ),
        migrations.CreateModel(
            name='WDmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wd_ids', models.CharField(blank=True, max_length=100, null=True)),
                ('wd_name', models.CharField(blank=True, max_length=100, null=True)),
                ('wd_address1', models.CharField(blank=True, max_length=150, null=True)),
                ('wd_address2', models.CharField(blank=True, max_length=150, null=True)),
                ('wd_address3', models.CharField(blank=True, max_length=150, null=True)),
                ('wd_address4', models.CharField(blank=True, max_length=150, null=True)),
                ('wd_postal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('wd_city', models.CharField(blank=True, max_length=100, null=True)),
                ('wd_state', models.CharField(blank=True, max_length=100, null=True)),
                ('wd_country', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('wd_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'master_wdmaster',
            },
        ),
        migrations.CreateModel(
            name='Weeklysales_update_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wd_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sku_id', models.CharField(blank=True, max_length=100, null=True)),
                ('wd_town_id', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_id', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_quantity', models.FloatField(blank=True, max_length=100, null=True)),
                ('new_quantity', models.FloatField(blank=True, max_length=100, null=True)),
                ('sales_type', models.CharField(blank=True, max_length=100, null=True)),
                ('month', models.CharField(blank=True, max_length=100, null=True)),
                ('week', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_category', models.CharField(blank=True, max_length=100, null=True)),
                ('sku_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sku_code', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'weekly_update_log',
            },
        ),
        migrations.CreateModel(
            name='BranchMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_address1', models.CharField(blank=True, max_length=150, null=True)),
                ('branch_address2', models.CharField(blank=True, max_length=150, null=True)),
                ('branch_address3', models.CharField(blank=True, max_length=150, null=True)),
                ('branch_city', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_postal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_country_code', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_country', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_state', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_code', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.CharField(blank=True, max_length=101, null=True, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('branch_ids', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'master_branchmaster',
            },
        ),
    ]
