# Generated by Django 3.2.9 on 2022-01-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='branchmaster',
            table='master_branchmaster',
        ),
        migrations.AlterModelTable(
            name='user',
            table='master_user',
        ),
        migrations.AlterModelTable(
            name='wdmaster',
            table='master_wdmaster',
        ),
    ]
