# Generated by Django 3.2.9 on 2022-01-17 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220117_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchmaster',
            old_name='created_on',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='branchmaster',
            old_name='last_modified_by',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='branchmaster',
            old_name='last_modified_on',
            new_name='last_updated_date',
        ),
        migrations.RenameField(
            model_name='wdmaster',
            old_name='created_on',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='wdmaster',
            old_name='last_modified_by',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='wdmaster',
            old_name='last_modified_on',
            new_name='last_updated_date',
        ),
    ]
