# Generated by Django 3.2.9 on 2022-01-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220117_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
