# Generated by Django 3.2.9 on 2022-02-11 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wdmaster',
            name='wd_id',
        ),
    ]
