# Generated by Django 3.2.9 on 2022-05-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_wdmaster_wd_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WDmaster',
        ),
    ]
