# Generated by Django 3.2.9 on 2022-05-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_delete_wdmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='WDmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wd_ids', models.CharField(blank=True, max_length=100, null=True)),
                ('wd_name', models.CharField(blank=True, max_length=100, null=True)),
                ('wd_address1', models.CharField(blank=True, max_length=150, null=True)),
                ('wd_address2', models.CharField(blank=True, max_length=150, null=True)),
                ('wd_address3', models.CharField(blank=True, max_length=150, null=True)),
                ('wd_address4', models.CharField(blank=True, max_length=150, null=True)),
                ('wd_postal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('wd_city', models.CharField(blank=True, max_length=100, null=True)),
                ('wd_state', models.CharField(blank=True, max_length=100, null=True)),
                ('wd_country', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('wd_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'master_wdmaster',
            },
        ),
    ]
