# Generated by Django 3.2.9 on 2022-06-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_wdmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=15, null=True)),
                ('user_type', models.CharField(blank=True, max_length=10, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'user_password_histrory',
            },
        ),
    ]
