# Generated by Django 3.2.9 on 2022-06-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20220617_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_status',
        ),
        migrations.AddField(
            model_name='user',
            name='last_acive_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='BlackListedToken',
        ),
    ]
