# Generated by Django 3.2.9 on 2022-09-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_user_raw_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=25, null=True)),
                ('user_type', models.CharField(blank=True, max_length=30, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('login_count', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'master_user_attendance',
            },
        ),
    ]
