# Generated by Django 3.2.9 on 2022-09-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_attendence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user_type', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_save_data', models.CharField(blank=True, max_length=100, null=True)),
                ('town_code', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'access_log',
            },
        ),
    ]
