# Generated by Django 3.2.9 on 2022-09-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20220915_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jjj',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
