# Generated by Django 3.2.9 on 2022-09-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20220915_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_reset_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='jjj',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reset_password_date',
        ),
    ]
