# Generated by Django 3.2.9 on 2022-09-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20220915_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_reset_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='jjj',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_date',
            field=models.DateField(blank=True, default=False, null=True),
        ),
    ]
