# Generated by Django 3.2.9 on 2022-09-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20220915_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reset_password_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
