# Generated by Django 3.2.9 on 2022-09-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20220915_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jjj',
        ),
    ]
