# Generated by Django 3.2.9 on 2022-11-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_user_jjj'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_reset_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
