# Generated by Django 3.2.9 on 2022-12-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20221202_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access_log',
            old_name='gpi_tate',
            new_name='gpi_state',
        ),
        migrations.RenameField(
            model_name='access_log',
            old_name='state',
            new_name='statename',
        ),
        migrations.RenameField(
            model_name='attendence',
            old_name='gpi_tate',
            new_name='gpi_state',
        ),
        migrations.RenameField(
            model_name='attendence',
            old_name='state',
            new_name='statename',
        ),
    ]
