# Generated by Django 3.2.9 on 2023-02-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20221202_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weeklysales_update_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wd_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sku_id', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_id', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('new_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_type', models.CharField(blank=True, max_length=100, null=True)),
                ('month', models.CharField(blank=True, max_length=100, null=True)),
                ('week', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
