# Generated by Django 3.2.9 on 2023-02-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_weeklysales_update_log_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklysales_update_log',
            name='brand_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weeklysales_update_log',
            name='sku_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weeklysales_update_log',
            name='sku_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='weeklysales_update_log',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weeklysales_update_log',
            name='wd_town_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weeklysales_update_log',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
