# Generated by Django 3.2.9 on 2023-02-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20230228_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklysales_update_log',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weeklysales_update_log',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
