# Generated by Django 3.2.9 on 2023-02-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_auto_20230228_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklysales_update_log',
            name='year',
        ),
    ]
