# Generated by Django 3.2.9 on 2023-02-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_remove_weeklysales_update_log_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklysales_update_log',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
