# Generated by Django 3.2.9 on 2023-03-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_weeklysales_update_log_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklysales_update_log',
            name='new_quantity',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='weeklysales_update_log',
            name='previous_quantity',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
