# Generated by Django 3.2.9 on 2022-05-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m1', models.CharField(max_length=25)),
                ('m2', models.CharField(max_length=25)),
                ('s', models.IntegerField()),
                ('f', models.IntegerField()),
            ],
        ),
    ]
