# Generated by Django 3.2.9 on 2022-05-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
