# Generated by Django 3.2.9 on 2022-05-09 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch_user', '0002_article_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
